### ISSUE TITLE
Issue with Inset text component 

### ISSUE THREAD

**Issue by tarikjohnston1** [simonwhatley/nhsuk-visual-studio-code-extension#31]
Format of inset text property key is incorrect 

{{ insetText({
  html: "Text"
}) }}

The HTML property key should be written as below as per Nunjucks 
https://service-manual.nhs.uk/design-system/components/inset-text

{{ insetText({
  **"HTML"**: "Text"
}) }}

**Comment by simonwhatley** [comment]
At the time of writing, the Nunjuck configuration for the inset component is correct, according to the NHS service manual.

For example, they state:

```
{% from 'inset-text/macro.njk' import insetText %}

{{ insetText({
  html: "<p>You can report any suspected side effect to the <a href=\"https://yellowcard.mhra.gov.uk/\" title=\"External website\">UK safety scheme</a>.</p>"
}) }}
```

The snippet, therefore, conforms to this convention.
